apiVersion: v1
kind: ReplicationController
metadata:
  name: ubuntu1604-agent-pool
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: ubuntu1604-agent-pool
        version: "0.1"
    spec:
      containers:
      - name: ubuntu1604-agent
        image: microsoft/vsts-agent:ubuntu-16.04-standard
        env:
          - name: VSTS_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: vsts
                key: VSTS_ACCOUNT
          - name: VSTS_TOKEN
            valueFrom:
              secretKeyRef:
                name: vsts
                key: VSTS_TOKEN
          - name: VSTS_POOL
            value: GCP Ubuntu 1604
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock